Check at configure time for unaligned reads required.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1769,6 +1769,49 @@ printf "%s\n" "$ac_res" >&6; }
   eval $as_lineno_stack; ${as_lineno_stack:+:} unset as_lineno
 
 } # ac_fn_c_check_func
+
+# ac_fn_c_try_run LINENO
+# ----------------------
+# Try to run conftest.$ac_ext, and return whether this succeeded. Assumes that
+# executables *can* be run.
+ac_fn_c_try_run ()
+{
+  as_lineno=${as_lineno-"$1"} as_lineno_stack=as_lineno_stack=$as_lineno_stack
+  if { { ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:${as_lineno-$LINENO}: $ac_try_echo\""
+printf "%s\n" "$ac_try_echo"; } >&5
+  (eval "$ac_link") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; } && { ac_try='./conftest$ac_exeext'
+  { { case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:${as_lineno-$LINENO}: $ac_try_echo\""
+printf "%s\n" "$ac_try_echo"; } >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; }
+then :
+  ac_retval=0
+else $as_nop
+  printf "%s\n" "$as_me: program exited with status $ac_status" >&5
+       printf "%s\n" "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+       ac_retval=$ac_status
+fi
+  rm -rf conftest.dSYM conftest_ipa8_conftest.oo
+  eval $as_lineno_stack; ${as_lineno_stack:+:} unset as_lineno
+  as_fn_set_status $ac_retval
+
+} # ac_fn_c_try_run
 ac_configure_args_raw=
 for ac_arg
 do
@@ -14489,6 +14532,67 @@ fi
 #
 # Checks for typedefs, structures, and compiler characteristics.
 
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking if pointers to integers require aligned access" >&5
+printf %s "checking if pointers to integers require aligned access... " >&6; }
+if test ${ax_cv_have_aligned_access_required+y}
+then :
+  printf %s "(cached) " >&6
+else $as_nop
+  if test "$cross_compiling" = yes
+then :
+  ax_cv_have_aligned_access_required=maybe
+else $as_nop
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+    #include <stdlib.h>
+int
+main (void)
+{
+
+                      int i;
+                      int *p;
+                      int *q;
+                      char *str;
+                      str = (char *) malloc(40);
+                      for (i = 0; i < 40; i++) {
+                        *(str + i) = i;
+                      }
+                      p = (int *) (str + 1);
+                      q = (int *) (str + 2);
+                      return (*p == *q);
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_run "$LINENO"
+then :
+  ax_cv_have_aligned_access_required=no
+else $as_nop
+  ax_cv_have_aligned_access_required=yes
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext \
+  conftest.$ac_objext conftest.beam conftest.$ac_ext
+fi
+
+fi
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ax_cv_have_aligned_access_required" >&5
+printf "%s\n" "$ax_cv_have_aligned_access_required" >&6; }
+
+if test "x$ax_cv_have_aligned_access_required" = "xmaybe"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Assuming aligned access is required when cross-compiling" >&5
+printf "%s\n" "$as_me: WARNING: Assuming aligned access is required when cross-compiling" >&2;}
+  ax_cv_have_aligned_access_required=yes
+fi
+
+if test "x$ax_cv_have_aligned_access_required" = "xyes"; then
+
+printf "%s\n" "#define HAVE_ALIGNED_ACCESS_REQUIRED 1" >>confdefs.h
+
+fi
+
+
 #--------------------------------------------------------------------------
 #
 # Checks for library functions.
@@ -14502,8 +14606,6 @@ CFLAGS="${CFLAGS}${CFLAGS+ }\$(CODE_COVERAGE_CFLAGS)"
 # Automake. (By the way, you often can use ‘$(eval ...)’ as well, but
 # @GNU@ here may be better.)
 
-
-#AC_CONFIG_HEADERS([config.h])
 
 { :;
   { :;
